import './globals.css'
import { Syne, DM_Sans } from 'next/font/google'
import Header from './components/Header'

const syne = Syne({ 
    subsets: ['latin'],
    variable: '--font-syne',
})

const dm_sans = DM_Sans({ 
    subsets: ['latin'],
    variable: '--font-dm_sans',
    weight: ['400', '500', '700'],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${syne.variable} ${dm_sans.variable} font-body`} >
                <div className='page-container'>
                    <Header />
                    {children}
                </div>
            </body>
        </html>
    )
}
